variables:
  VERSION: "$CI_COMMIT_TAG"

stages:
  - build
  - deploy
  - release

build:
  image: maven:3-jdk-11
  stage: build
  script:
    - "mvn clean install"
  artifacts:
    expire_in: 24 hour
    paths:
      - target/engine-*.jar
  tags:
    - s0ra

deploy manual:
  image: docker
  stage: deploy
  dependencies:
    - build
  environment:
    name: development
  services:
    - docker:19.03.1-dind
  when: manual
  script:
    - "docker build -t registry.gitlab.com/colivery1/colivery-engine:latest ."
    - "docker push registry.gitlab.com/colivery1/colivery-engine:latest"
  before_script:
    - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
  after_script:
    - "docker logout $CI_REGISTRY"
  except:
    - develop
    - tags
  tags:
    - s0ra

deploy:
  image: docker
  stage: deploy
  dependencies:
    - build
  environment:
    name: development
  services:
    - docker:19.03.1-dind
  script:
    - "docker build -t registry.gitlab.com/colivery1/colivery-engine:${version} ."
    - "docker build -t registry.gitlab.com/colivery1/colivery-engine:latest ."
    - "docker push registry.gitlab.com/colivery1/colivery-engine:${version}"
    - "docker push registry.gitlab.com/colivery1/colivery-engine:latest"
  before_script:
    - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
  after_script:
    - "docker logout $CI_REGISTRY"
  only:
    - develop
  tags:
    - s0ra


deploy automatically on master:
  image: docker
  stage: deploy
  dependencies:
    - build
  environment:
    name: stage
  services:
    - docker:19.03.1-dind
  script:
    - "docker build -t registry.gitlab.com/colivery1/colivery-engine:latest ."
    - "docker push registry.gitlab.com/colivery1/colivery-engine:latest"
  before_script:
    - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
  after_script:
    - "docker logout $CI_REGISTRY"
  only:
    - tags
  tags:
    - s0ra


deploy with tags:
  image: docker
  stage: release
  dependencies:
    - build
  environment:
    name: stage
  services:
    - docker:19.03.1-dind
  script:
    - "mvn versions:set -DnewVersion=${CI_COMMIT_TAG}"
    - "docker build -t registry.gitlab.com/colivery1/colivery-engine:${CI_COMMIT_TAG} ."
    - "docker build -t registry.gitlab.com/colivery1/colivery-engine:latest ."
    - "docker push registry.gitlab.com/colivery1/colivery-engine:${CI_COMMIT_TAG}"
    - "docker push registry.gitlab.com/colivery1/colivery-engine:latest"
  before_script:
    - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
  after_script:
    - "docker logout $CI_REGISTRY"
  only:
    - tags
  tags:
    - s0ra
